paginas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('detalhe/n°<int:id>',views.detalhe, name='detalhe'),
    path('anunciar/',views.anunciar, name='anunciar'),
    path('suporte/', views.suporte, name='suporte'),
    path('meus_anúncios/', views.meu_anuncio, name="meu_anuncio"),
    path('Animais_de_Estimação/', views.animais, name="animais"),
    path('Eletrodomésticos/', views.eletrodomestico, name="eletro"),
    path('Eletrônicos_e_Celulares/', views.eletronico, name="eletronico"),
    path('Festas_e_Eventos/', views.festa, name="festa"),
    path('Imóveis/', views.imovel, name="imovel"),
    path('Moda_e_Beleza/', views.moda, name="moda"),
    path('Serviços/', views.servico, name="servico"),
    path('Veículos_e_Peças/', views.veiculo, name="veiculo"),
    path('Vagas_de_Emprego/', views.vaga, name="vaga"),
    path('buscar/', views.buscar, name="buscar")
    
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/models.py
from django.db import models
from django.contrib.auth.models import User

class CategoriaItem(models.Model):
    nome = models.CharField(max_length=50)
    def __str__(self):
        return self.nome


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tudo')
    titulo    = models.CharField(max_length=30)
    descricao = models.TextField(blank=True)
    categoria = models.ForeignKey(CategoriaItem, on_delete=models.CASCADE, blank=False)
    foto      = models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')
    foto2     = models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')
    foto3     = models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')
    cidade    = models.CharField(max_length=30)
    bairro    = models.CharField(max_length=30)
    contato   = models.CharField(max_length=20)
    contato2  = models.CharField(max_length=20, blank=True)
    valor     = models.CharField(max_length=20)
    data      = models.CharField(max_length=8, blank=True)
    ativo     = models.BooleanField(default=True)
    def __str__(self):
        return self.titulo
    
    
class Feedback(models.Model):
    option = [
        ('Sugestâo', 'Sugestão'),
        ('Reclamação', 'Reclamação'),
        ('Parceria', 'Parceria'),
        ('Outro','Outro')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    motivo    = models.CharField(max_length=10, choices=option)
    descricao = models.TextField()
    def __str__(self):
        return self.motivo

paginas/forms.py
from django import forms
from django.forms import widgets
from django.forms.widgets import Widget 
from .models import Feedback, Item, CategoriaItem

class Task(forms.ModelForm):
    class Meta:
        city = [('Soure','Soure'),
                ('Salvaterra','Salvaterra')]
        model = Item
        fields = ['titulo', 'categoria', 'valor', 'descricao', 'cidade', 'bairro', 'foto',
                  'foto2', 'foto3', 'contato', 'contato2']
        widgets = {
            'cidade': forms.Select(choices=city),
        }

class Task2(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['motivo', 'descricao',]
        

        

paginas/views.py
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from .models import Feedback, Item, CategoriaItem
from django.contrib.auth.models import User
from .forms import Task, Task2
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.core.paginator import Paginator



@login_required(redirect_field_name='login')
def index(request):
    anuncios = Item.objects.all().order_by('-id').filter(ativo=True)
    paginator = Paginator(anuncios, 20)
    page = request.GET.get('p')
    anuncios = paginator.get_page(page)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})






@login_required(redirect_field_name='login')
def detalhe(request, id):
    item = get_object_or_404(Item, id=id)
    return render(request, 'paginas/mostrar.html', {'item': item})

@login_required(redirect_field_name='login')
def anunciar(request):
    if request.method == "POST":
        titulo = request.POST.get('titulo')
        categoria = request.POST.get('categoria')
        valor = request.POST.get('valor')
        descricao = request.POST.get('descricao')
        cidade = request.POST.get('cidade')
        bairro = request.POST.get('bairro')
        foto = request.FILES.get('foto')
        foto2 = request.FILES.get('foto2')
        foto3 = request.FILES.get('foto3')
        contato = request.POST.get('contato')
        contato2 = request.POST.get('contato2')
        user = get_object_or_404(User, pk=request.user.id)
        
        
        add = Item.objects.create(titulo=titulo, categoria_id=categoria, valor=valor,
                                  descricao=descricao, cidade=cidade, bairro=bairro,
                                  foto=foto, foto2=foto2, foto3=foto3, contato=contato,
                                  contato2=contato2, user=user, data=datetime.now().strftime("%d/%m/%Y"))
        add.save()
        return redirect('home')
    else:
        return render(request, 'paginas/anunciar.html')



@login_required(redirect_field_name='login')
def suporte(request):
    
    if request.method == 'POST':
        motivo = request.POST.get('motivo')
        descricao = request.POST.get('descricao')
        user = get_object_or_404(User, pk=request.user.id)
        add = Feedback.objects.create(user=user, motivo=motivo, descricao=descricao)
        add.save()
        return redirect('home')
    
    else:        
        return render(request, 'paginas/suporte.html')


@login_required(redirect_field_name='login')
def meu_anuncio(request):
    tudo = Item.objects.filter(user_id=request.user.id)
    return render(request, 'paginas/meu_anuncio.html', {'tudo':tudo})


@login_required(redirect_field_name='login')
def animais(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=3,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def eletrodomestico(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=4,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def eletronico(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=5,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def festa(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=6,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def imovel(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=7,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def moda(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=8,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def servico(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=9,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def veiculo(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=10,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def vaga(request):
    anuncios = Item.objects.all().order_by('-id').filter(categoria=11,ativo=True)
    return render(request, 'paginas/index.html', {'anuncios': anuncios})

@login_required(redirect_field_name='login')
def buscar(request):
    termo = request.GET.get('termo')
    anuncios = Item.objects.order_by('-id').filter(titulo__icontains=termo,ativo=True)
    resultados = anuncios.count()
    return render(request, 'paginas/buscar.html', {'anuncios': anuncios, 'resultados':resultados})

paginas/templates/paginas/anunciar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%load static%}

{%block 'conteudo'%}


<form  style="height:980px;" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
 
    <div id="div_id_titulo" class="form-group">
        <label for="id_titulo" class=" requiredField">Titulo<span class="asteriskField">*</span> </label>
        <input type="text" name="titulo" maxlength="30" class="textinput textInput form-control" required id="id_titulo">  
    </div> 
    <div id="div_id_categoria" class="form-group">
        <label for="id_categoria" class=" requiredField">Categoria<span class="asteriskField">*</span></label>
        <select name="categoria" class="select form-control" required id="id_categoria">
                <option value="3">Animais de Estimação</option>
                <option value="4">Eletrodomésticos</option>
                <option value="5">Eletrônicos e Celulares</option>
                <option value="6">Festas e Eventos</option>
                <option value="7">Imóveis</option>
                <option value="8">Moda e Beleza</option>
                <option value="9">Serviços</option>
                <option value="10">Veículos e Peças</option>
                <option value="11">Vagas de Emprego</option>

        </select> 
    </div>
    <div id="div_id_valor" class="form-group">
        <label for="id_valor" class=" requiredField">Valor<span class="asteriskField">*</span></label>
        <input type="number" name="valor" class="numberinput form-control" required id="id_valor">
    </div>
    <div id="div_id_descricao" class="form-group"> <label for="id_descricao" class=" requiredField">Descricao<span class="asteriskField">*</span> </label>
        <textarea name="descricao" cols="40" rows="10" class="textarea form-control" required id="id_descricao"></textarea> 
    </div>
    <div id="div_id_cidade" class="form-group"> <label for="id_cidade" class=" requiredField">Cidade<span class="asteriskField">*</span></label>
        <select name="cidade" maxlength="30" class="select form-control" id="id_cidade">
            <option value="Soure">Soure</option>
            <option value="Salvaterra">Salvaterra</option>

        </select> 
    </div>
    <div id="div_id_bairro" class="form-group">
        <label for="id_bairro" class=" requiredField">Bairro<span class="asteriskField">*</span></label>
        <input type="text" name="bairro" maxlength="30" class="textinput textInput form-control" required id="id_bairro">
    </div>
    <div id="div_id_foto" class="form-group">
        <label for="id_foto" class="">Foto</label>
        <input type="file" name="foto" accept="image/*" class="clearablefileinput form-control-file" id="id_foto">
    </div> 
    <div id="div_id_foto2" class="form-group">
        <label for="id_foto2" class="">Foto2</label>
        <input type="file" name="foto2" accept="image/*" class="clearablefileinput form-control-file" id="id_foto2">
    </div>
    <div id="div_id_foto3" class="form-group">
        <label for="id_foto3" class="">Foto3</label> 
        <input type="file" name="foto3" accept="image/*" class="clearablefileinput form-control-file" id="id_foto3">
    </div>
    <div id="div_id_contato" class="form-group">
        <label for="id_contato" class=" requiredField">Contato<span class="asteriskField">*</span></label>
        <input type="text" name="contato" maxlength="20" class="textinput textInput form-control" required id="id_contato">
    </div>
    <div id="div_id_contato2" class="form-group">
        <label for="id_contato2" class="">Contato2</label>
        <input type="text" name="contato2" maxlength="20" class="textinput textInput form-control" id="id_contato2">
    </div>
    <button style="margin-left:36%;" class="btn btn-success" type="submit">Anunciar</button>

</form>


{%endblock%}

paginas/templates/paginas/buscar.html
{%extends 'paginas/index.html'%}
{%load static%}

paginas/templates/paginas/cadastro.html
<!doctype html>
{%load static%}
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cadastro</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'signin.css'%}" rel="stylesheet">
  </head>
  <body class="text-center">
    <main style="margin-top:0%;" class="form-signin">
    <form method="POST">
        {% csrf_token %}
        <h1 align="center">Cadastro</h1>

        {% if messages %}
          
              {% for message in messages %}
              <h4 style="color:red;" align="center" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
              {% endfor %}
          
        {% endif %}

        <div class="form-floating">
        <input style="margin-left:10%; width:80%;" class="form-control" id="floatingInput" placeholder="Nome de usuário" name="usu" value="{{request.POST.usu}}">
        <input style="margin-left:10%; width:80%;" type="number" class="form-control" id="floatingInput" placeholder="Número para Contato" name="numero">  
        </div>
        <div class="form-floating">
        <input style="margin-left:10%; width:80%;" type="password" class="form-control" id="floatingPassword" placeholder="Senha" name="senha">
        <input style="margin-left:10%; width:80%;" type="password" class="form-control" id="floatingPassword" placeholder="Repita sua Senha" name="senha2">
        </div>
        <button style="margin-left:40%; height:30px; border-radius:5px; background-color:green; color:white;" class="w-100 btn btn-lg btn-primary" type="submit"><b>Cadastrar</b></button>
        
    </form>
    </main>

  </body>
</html>

paginas/templates/paginas/index.html
{%extends 'base.html'%}
{%load static%}

{%block 'conteudo'%}


 
<div class="col-lg-6">
  {%for i in anuncios%}  
  <div  class="flex-md-row mb-4 box-shadow h-xl-300">
    <a href="{%url 'detalhe' i.id%}">
      <div style="background-color:#D3D3D3;border-radius:5px 5px 0px 5px;" class="mb-3 d-flex align-items-center">
      {%if i.foto%}
      <img style="border-radius:5px 0px 0px 5px;" height="85" width="120" src="{{i.foto.url}}">
      {%else%}
      <img style="border-radius:5px 0px 0px 5px;" height="85" width="120" src="{% static 'img/unnamed.jpg'%}">
      {%endif%}
      <div class="pl-3">
        <h2 style="padding-top:4%; font-family:Garamond;" class="mb-2 h6 font-weight-bold">
        <a style="color:black;" href="{%url 'detalhe' i.id%}">{{i.titulo}}</a>
        </h2>
      <div class="card-text text-muted small">
          <h6 style="color:black; opacity:0.7; font-family:Garamond;"><b>R$ {{i.valor}}</b></h6>
      </div>
        <small class="text-muted">{{i.cidade}}/{{i.bairro}} </small>
        
      </div>
  </div></a>
  {%endfor%}
  

  
  <div class="pagination">
    <span class="step-link">
    
      {%if anuncios.has_previous%}
        <a href="?p={{anuncios.previous_page_number}}"><img src="{% static 'img/2.ico'%}" width=35px></a>
      {%endif%}

      <span class="current">
        {{anuncios.number}} de {{anuncios.paginator.num_pages}}
      </span>

      {%if anuncios.has_next%}
        <a href="?p={{anuncios.next_page_number}}"><img src="{% static 'img/1.ico'%}" width=35px></a>
      {%endif%}
    </span>
  </div>

  


{%endblock%}

paginas/templates/paginas/login.html
<!doctype html>
{%load static%}
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Login</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'signin.css'%}" rel="stylesheet">
  </head>
  <body class="text-center">

<main style="margin-top:0%;" class="form-signin">
  <form method="POST">
    {% csrf_token %}
    <img style="width:100px; height:100px; margin-left:35%;" class="mb-4" src="Mask Group.jpg" alt="" >
    {% if messages %}
          
              {% for message in messages %}
              <h4 style="color:red;" align="center" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
              {% endfor %}
          
        {% endif %}


    <div class="form-floating">
      <input style="margin-left:10%; width:80%;" name="usuario" class="form-control" id="floatingInput" placeholder="Usuário. Ex: Carlos123">
    </div>
    <div class="form-floating">
      <input style="margin-left:10%; width:80%;" name="senha" type="password" class="form-control" id="floatingPassword" placeholder="Senha">
    </div>
    <button style="margin-left:42%; height:30px; border-radius:5px;" class="w-100 btn btn-lg btn-primary" type="submit">Entrar</button>
    <p align="center">Ainda não está cadastrado?</p> 
    <p align="center">Então Vemtibora <a href="{% url 'cadastro'%}">clique aqui</a></p>
    <p align="center" class="mt-5 mb-3 text-muted">&copy; 2021–2022</p>
  </form>
</main>



  </body>
</html>

paginas/templates/paginas/meu_anuncio.html
{%extends 'base.html'%}
{%load static%}

{%block 'conteudo'%}

<table style="width:90%; margin-top:0%;" class="table">
    <thead>
      <tr>
        <th style="text-align:center;" scope="col">Título</th>
        <th style="text-align:center;" scope="col">Vender</th>
      </tr>
    </thead>
    <tbody>
        {%for i in tudo%}
      <tr>
        
        <td style="text-align:center;">{{i}}</td>
        <td style="text-align:center;"><a href="{% url 'vender' i.id%}"><img src="{% static 'img/vender.png'%}" style="width:35px;"><a/></td>
      </tr>
        {%endfor%}
    </tbody>
  </table>

{%endblock%}

paginas/templates/paginas/mostrar.html
{%extends 'base.html'%}
{%load static%}

{% block 'conteudo'%}



<div style="margin-top:-3%;" id="carouselExampleControlsNoTouching" class="carousel slide" data-bs-touch="true" data-bs-interval="false">
    <div class="carousel-inner">
      <div class="carousel-item active">
        {%if item.foto%}
        <img style="width:100%; height:180px;" src="{{item.foto.url}}" class="d-block w-100" alt="...">
        {% else %}
        <img style="width:100%; height:180px;" src="{%static 'img/unnamed.jpg'%}" class="d-block w-100" alt="...">
        {%endif%}
      </div>
      {%if item.foto2%}
      <div class="carousel-item">
        <img style="width:100%; height:180px;" src="{{item.foto2.url}}" class="d-block w-100" alt="">
      </div>
      {%endif%}
      {%if item.foto3%}
      <div class="carousel-item">
        <img style="width:100%; height:180px;" src="{{item.foto3.url}}" class="d-block w-100" alt="">
      </div>
      {%endif%}
    </div>
    {%if item.foto2%}
    <button style="background-color:black; opacity:0.8; height:30px; width:30px; margin-top:18%; margin-left:1%;" class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button style="background-color:black; opacity:0.8; height:30px; width:30px; margin-top:18%; margin-right:1%;" class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    {%endif%}
  </div>

  <div style="border: 1px solid; border-radius:15px;margin-top:2%;">
  <h3 style="margin-left:3%; margin-top:2%;">{{item.titulo}}</h3>    
  <h5 style="margin-left:3%; margin-top:2%;">R$ {{item.valor}}</h1>
  </div>
  <div style="border: 1px solid;border-radius:15px; margin-top:2%;">
  <h3 style="margin-left:3%; margin-top:2%;">Descrição</h3>
  <h5 style="margin-left:3%; margin-top:2%; Word-wrap: break-Word; white-space: normal; padding-right:2%;" >{{item.descricao}}</h5>
  </div>
  <div style="border: 1px solid;border-radius:15px; margin-top:2%;">
  <h3 style="margin-left:3%; margin-top:2%;">Detalhes</h3>
  <h5 style="margin-left:3%; margin-top:2%; Word-wrap: break-Word; white-space: normal; padding-right:2%;" >{{item.cidade}}/{{item.bairro}}</h5>
  <h5 style="margin-left:3%; margin-top:2%; Word-wrap: break-Word; white-space: normal; padding-right:2%;" >Contato: {{item.contato}}</h5>
  {%if contato2%}
  <h6 style="margin-left:3%; margin-top:2%; Word-wrap: break-Word; white-space: normal; padding-right:2%;" >Contato2: {{item.contato2}}</h6>
  {%endif%}
  <h6 style="margin-left:3%; margin-top:2%; Word-wrap: break-Word; white-space: normal; padding-right:2%;" >Data:{{item.data}}</h6>

  </div>

{%endblock%}

paginas/templates/paginas/suporte.html
{%extends 'base.html'%}
{%load static%}
{%load crispy_forms_tags%}

{%block 'conteudo'%}

<form method="POST">
    {% csrf_token %}

    <div class="sup-diff">
        <h5>Motivo</h5>
        <select style="border-radius:8px; text-align:center; height:30px;" name="motivo">
            <option>Sugestâo</option>
            <option>Reclamação</option>
            <option>Parceria</option>
            <option>Outro</option>
        </select>

        <h5 style=" margin-top:8%;">Descrição</h5>
        <textarea style="border-radius:8px; height:150px; width:90%;" type="text" name="descricao"></textarea>
        <button class="btn btn-success" style="margin-left:30%;">Enviar</button>
    </div>

</form>

{%endblock%}